### ISSUE TITLE
[Code Signing Certificate]: BootstrapBlazor

### ISSUE THREAD

**Issue by ArgoZhang** [dotnet-foundation/projects#422]
### Project Name

BootstrapBlazor

### LastPass Email

argo@live.ca

### Onboarding Checklist

- [ ] Register trade name @ChrisSfanos
- [ ] Create configuration in Code Signing Service
- [ ] Create organization with DigiCert
- [ ] Request certificate from DigiCert
- [ ] Received certificate and finalize sign service configuration
- [ ] Provide credentials in shared folder in LastPass

**Comment by ArgoZhang** [comment]
@ChrisSfanos I am very sorry to bother you, can you help me solve this problem? I cannot release a new version because it is not signed.

the github action got 400 status 

```
Service request failed.
Status: 400 (Bad Request)
```

link action

https://github.com/dotnetcore/BootstrapBlazor/actions/runs/12976258898/job/36189550018?wt.mc_id=DT-MVP-5004174

**Comment by ChrisSfanos** [comment]
Hi @ArgoZhang  - the process to onboard a new project into the signing infrastructure takes a bit of time - we will not have a certificate available for you immediately.  I will be starting the cert request process tomorrow (registering the Trade name with the State of Washington and getting that into the DigiCert systems is definitely not an immediate process)

**Comment by ArgoZhang** [comment]
@ChrisSfanos sure. thank you very much. We will wait for the process to complete.

**Comment by ArgoZhang** [comment]
@ChrisSfanos first thank you very much for the help. Has there been any progress on the certificate application?

**Comment by ChrisSfanos** [comment]
Yes, but not there yet - I'm going to be checking on this this week - thanks

**Comment by ArgoZhang** [comment]
@ChrisSfanos great!



```
Running Azure CLI Login.
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n azurecloud"
Done setting cloud: "azurecloud"
Federated token details:
 issuer - [https://token.actions.githubusercontent.com](https://token.actions.githubusercontent.com/?wt.mc_id=DT-MVP-5004174)
 subject claim - repo:dotnetcore/BootstrapBlazor:ref:refs/heads/test
Attempting Azure CLI login by using OIDC...
Error: AADSTS70025: The client '***'(Code Sign - BootstrapBlazor) has no configured federated identity credentials. Trace ID: b[20](https://github.com/dotnetcore/BootstrapBlazor/actions/runs/13731585867/job/38409567839?wt.mc_id=DT-MVP-5004174#step:5:21)703f5-6964-49fe-9260-b21066c43f00 Correlation ID: 7bd62670-c7c8-4573-8252-62e82603a539 Timestamp: 2025-03-08 00:10:25Z

Error: Interactive authentication is needed. Please run:
az login

Error: Login failed with Error: The process 'C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
```

According to the prompt 

```
Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
```

update the `auth-type` to `IDENTITY`

got the following error

```
Attempting Azure CLI login by using user-assigned managed identity...
Error: Failed to connect to MSI, check your managed service identity id.

Error: Login failed with Error: The process 'C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to [https://github.com/Azure/login#readme](https://github.com/Azure/login#readme?wt.mc_id=DT-MVP-5004174) for more information.
```

I don't know where the problem is. Could you help me take a look?

**Comment by ArgoZhang** [comment]
@ChrisSfanos Sorry to bother you again. From the GitHub action log, we can see that we cannot log in to Azure based on the information provided. We are currently stuck at this step.


https://github.com/dotnetcore/BootstrapBlazor/actions/runs/13779442048/job/38534935612?wt.mc_id=DT-MVP-5004174

**Comment by glennawatson** [comment]
That's a configuration issue on our side we were through last time with json everything.

**Comment by ArgoZhang** [comment]
@glennawatson Do we just need to wait for you to configure something further?

**Comment by glennawatson** [comment]
yeah, will have to be our side.

**Comment by ChrisSfanos** [comment]
I'd like to get back to this on Monday - we have made some progress on getting these working.  I created a GitHub Federated cred for you for us to get started

**Comment by ArgoZhang** [comment]
@ChrisSfanos Do you know if I need to make any configuration changes? Still can't log in to Azure.

You can get more information by following the link

https://github.com/dotnetcore/BootstrapBlazor/actions/runs/14505284024/job/40693559909?wt.mc_id=DT-MVP-5004174

**Comment by ArgoZhang** [comment]
@ChrisSfanos 

I'm so sorry to bother you. failed login AZ again
https://github.com/dotnetcore/BootstrapBlazor/actions/runs/14543792039/job/40806338246?wt.mc_id=DT-MVP-5004174

**Comment by ChrisSfanos** [comment]
Apparently the Federated credential is case sensitive, so I corrected that.  You should be able to try again

**Comment by ArgoZhang** [comment]
@ChrisSfanos I tried again. I found that the error message has changed. But I still can't log in to AZ. I guess there is something wrong with the configuration.

https://github.com/dotnetcore/BootstrapBlazor/actions/runs/14583926715/job/40905981359?wt.mc_id=DT-MVP-5004174

**Comment by ChrisSfanos** [comment]
What auth type are you using?  Other folks who have been working through issues have been posting on Discord here - https://discord.com/channels/966483029830824008/966484831091449856 - Project-support channel.  Might be able to get better (more experienced) help there
